const { chromium } = require('C:/Users/xiaoxiami/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs');
(async () => {
  fs.mkdirSync('.qa', { recursive: true });
  const browser = await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true,args:['--autoplay-policy=no-user-gesture-required']});
  const page = await browser.newPage({viewport:{width:1440,height:900},deviceScaleFactor:1});
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  page.on('console',message=>{if(message.type()==='error')errors.push(message.text()+' '+message.location().url);});
  page.on('response',response=>{if(response.status()>=400)errors.push(response.status()+' '+response.url());});
  await page.goto('http://127.0.0.1:5173');
  await page.waitForFunction(()=>window.__squish);
  await page.screenshot({path:'.qa/initial.png'});
  await page.mouse.move(865,480);await page.mouse.down();await page.waitForTimeout(1400);
  const pressed=await page.evaluate(()=>window.__squish.state);
  await page.screenshot({path:'.qa/pressed.png'});
  assert(pressed.down && pressed.maxIndent>.08 && pressed.cracks>0,JSON.stringify(pressed));
  await page.mouse.move(940,510,{steps:12});await page.waitForTimeout(300);
  await page.mouse.up();
  const released=await page.evaluate(()=>window.__squish.state);
  assert(released.maxIndent>.02,'No slow rebound');
  await page.waitForTimeout(3100);
  const recovered=await page.evaluate(()=>window.__squish.state);
  assert(recovered.maxIndent<.015,'Did not recover');assert(recovered.cracks>=pressed.cracks,'Cracks disappeared');
  await page.screenshot({path:'.qa/recovered.png'});
  await page.click('#sound');assert.equal(await page.getAttribute('#sound','aria-pressed'),'false');
  await page.click('#reset');await page.waitForTimeout(600);
  assert.equal((await page.evaluate(()=>window.__squish.state)).cracks,0);
  assert.equal(await page.evaluate(()=>document.documentElement.scrollHeight>innerHeight),false);
  await page.setViewportSize({width:1440,height:810});await page.screenshot({path:'.qa/widescreen.png'});
  await page.setViewportSize({width:390,height:844});await page.screenshot({path:'.qa/mobile.png'});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
  const mobile=await browser.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true});
  await mobile.goto('http://127.0.0.1:5173');await mobile.waitForFunction(()=>window.__squish);
  const cdp=await mobile.context().newCDPSession(mobile);
  await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:195,y:460}]});await mobile.waitForTimeout(800);
  assert((await mobile.evaluate(()=>window.__squish.state)).down,'Touch did not press');
  await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});
  assert.equal((await mobile.evaluate(()=>window.__squish.state)).down,false);
  console.log(JSON.stringify({pressed,released,recovered,errors},null,2));
  await browser.close();assert.equal(errors.length,0);
})().catch(e=>{console.error(e);process.exit(1);});
